// game
const CREATE_NEW_GAME = "CREATE_NEW_GAME";
const EXIT_FROM_GAME = "EXIT_FROM_GAME";
// list
const GET_GAMES_LIST = "GET_GAMES_LIST";
const REFRESH_GAMES_LIST = "REFRESH_GAMES_LIST";

module.exports = {
  CREATE_NEW_GAME,
  EXIT_FROM_GAME,
  GET_GAMES_LIST,
  REFRESH_GAMES_LIST
};
