// server

const NEW_MESSAGE = "NEW_MESSAGE";
// game
const CREATE_NEW_GAME = "CREATE_NEW_GAME";
const CREATED_NEW_GAME = "CREATED_NEW_GAME";
const JOIN_GAME = "JOIN_GAME";
const EXIT_FROM_GAME = "EXIT_FROM_GAME";
const UPDATE_BOARD = "UPDATE_BOARD";

// list
const GET_GAMES_LIST = "GET_GAMES_LIST";
const RECEIVED_GAMES_LIST = "RECEIVED_GAMES_LIST";
const REFRESH_GAMES_LIST = "REFRESH_GAMES_LIST";
// player

const PLAYER_MOVE = "PLAYER_MOVE";

module.exports = {
  CREATE_NEW_GAME,
  CREATED_NEW_GAME,
  EXIT_FROM_GAME,
  GET_GAMES_LIST,
  REFRESH_GAMES_LIST,
  PLAYER_MOVE,
  JOIN_GAME,
  NEW_MESSAGE,
  RECEIVED_GAMES_LIST,
  UPDATE_BOARD
};
